/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IExerciceSolutionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimTokensOnBehalf"
      | "depositTokens"
      | "getERC20DepositAddress"
      | "tokensInCustody"
      | "withdrawTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimTokensOnBehalf",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getERC20DepositAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokensInCustody",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawTokens",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimTokensOnBehalf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getERC20DepositAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensInCustody",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawTokens",
    data: BytesLike
  ): Result;
}

export interface IExerciceSolution extends BaseContract {
  connect(runner?: ContractRunner | null): IExerciceSolution;
  waitForDeployment(): Promise<this>;

  interface: IExerciceSolutionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimTokensOnBehalf: TypedContractMethod<[], [void], "nonpayable">;

  depositTokens: TypedContractMethod<
    [amountToWithdraw: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getERC20DepositAddress: TypedContractMethod<[], [string], "nonpayable">;

  tokensInCustody: TypedContractMethod<
    [callerAddress: AddressLike],
    [bigint],
    "nonpayable"
  >;

  withdrawTokens: TypedContractMethod<
    [amountToWithdraw: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimTokensOnBehalf"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositTokens"
  ): TypedContractMethod<
    [amountToWithdraw: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getERC20DepositAddress"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "tokensInCustody"
  ): TypedContractMethod<[callerAddress: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawTokens"
  ): TypedContractMethod<
    [amountToWithdraw: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
