/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Claimable } from "./ERC20Claimable";
export type { ERC20TD } from "./ERC20TD";
export type { Evaluator } from "./Evaluator";
export type { IERC20Mintable } from "./IERC20Mintable";
export type { IExerciceSolution } from "./IExerciceSolution";
